name: 'autopush'

#TODO Make secrets:
        gcloud run services update ${{ env.AUTOPUSH_CLOUD_RUN_SERVICE_NAME }} \
        --project="${{ env.AUTOPUSH_PROJECT_ID }}" \


on:
  push:
    branches:
    - 'main'
    - 'release/**/*'

permissions:
  contents: 'read'
  id-token: 'write'

env:
  DOCKER_REGISTRY: 'us-docker.pkg.dev'
  DOCKER_REPO: 'us-docker.pkg.dev/abc-updater-p-95/abc-updater-images'
  IMAGE_NAME: 'abc-updater-metrics-server'
  CLOUD_RUN_SERVICE_REGION: 'us-central1'

# Do not cancel in progress to prevent half baked release.
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'

jobs:
  build_autopush:
    runs-on: 'ubuntu-latest'
    environment: 'wif'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c' # ratchet:google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.wif_provider }}'
        service_account: '${{ secrets.wif_service_account_email }}'
        token_format: 'access_token'
    - name: 'Authenticate to Artifact Registry'
      uses: 'docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d' # ratchet:docker/login-action@v3
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.DOCKER_REGISTRY }}'
    - name: 'Build Integration Container'
      run: |-
        docker buildx build \
          -t ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --no-cache .
    - name: 'Tag Image With Commit Sha'
      run: |-
        docker image tag ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.sha || github.sha }}
    - name: 'Tag Image With Autopush'
      # TODO: we should probably only do this for images on main.
      run: |-
        docker image tag ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:autopush
    - name: 'Push Image to Artifact Registry'
      run: |-
        docker push --all-tags ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
